// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayServicesConstants
{
        public const string achievement_level_1 = "CgkI7_HM3tYLEAIQAw"; // <GPGSID>
        public const string achievement_level_2 = "CgkI7_HM3tYLEAIQBA"; // <GPGSID>
        public const string achievement_level_3 = "CgkI7_HM3tYLEAIQBQ"; // <GPGSID>
        public const string achievement_level_4 = "CgkI7_HM3tYLEAIQBg"; // <GPGSID>
        public const string achievement_level_5 = "CgkI7_HM3tYLEAIQBw"; // <GPGSID>
        public const string achievement_level_6 = "CgkI7_HM3tYLEAIQCA"; // <GPGSID>
        public const string achievement_level_7 = "CgkI7_HM3tYLEAIQCQ"; // <GPGSID>
        public const string achievement_level_8 = "CgkI7_HM3tYLEAIQCg"; // <GPGSID>
        public const string achievement_level_9 = "CgkI7_HM3tYLEAIQCw"; // <GPGSID>
        public const string achievement_level_10 = "CgkI7_HM3tYLEAIQDA"; // <GPGSID>
        public const string BUNDLE_ID = "lu.zor.boxy5"; // <GPGSID>
        public const string leaderboard_leadership = "CgkI7_HM3tYLEAIQAg"; // <GPGSID>

}

